name: algokit
description: A versatile Dart algorithms library providing implementations of various algorithms..
version: 1.0.1
homepage: https://github.com/vijaykarthiktk/algokit
repository: https://github.com/vijaykarthiktk/algokit

environment:
  sdk: ^3.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
