name: algorithms
description: A versatile Dart algorithms library providing implementations of various algorithms..
version: 1.0.0
homepage: https://github.com/vijaykarthiktk/algorithms
repository: https://github.com/vijaykarthiktk/algorithms

environment:
  sdk: ^3.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
